name: Waka Readme

on:
  push:
    branches:
      # - nothing # Should never run
      # - main
      - dev
  schedule:
    - cron: '0 */24 * * *' # every 24 hours
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.USER_TOKEN }}  # Github PAT
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "True" 
          SHOW_OS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_UPDATED_DATE: "True"