# The purpose of this workflow is to gernate updated stat for my readme.md on a recurring basis.
# Here is a link to the workflow: https://github.com/marketplace/actions/profile-readme-development-stats

name: Waka Readme

on:
  push:
    branches:
      - nothing # Should never run
#       - main
#        - dev
  schedule:
    - cron: '0 18 * * *' # every 24 hours
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
#       - uses: anmol098/waka-readme-stats@v4  # How to use a tag
      - uses: anmol098/waka-readme-stats@f8cec5f73e6f2a551a25da883d849b06f471a918 # Master as of March 31, 2022
        with:
          LOCALE: "en"  # en_US does not work 
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.USER_TOKEN }}  # Github PAT
          COMMIT_MESSAGE: "Automatically Updated README.md" # Not valid on @v4, doesn't work on @master
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False" 
          SHOW_OS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TIMEZONE: "False"
          SHOW_LANGUAGE: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_SHORT_INFO: "True"
          UPDATED_DATE_FORMAT: "%m/%d/%Y %H:%M"  # Waiting for a release tag which supports this feature
          SHOW_TOTAL_CODE_TIME: "False"
#           SHOW_UPDATED_DATE: "True"  # Enabled by default
