# The purpose of this workflow is to update my Wakatime image my readme.md on a recurring basis and cache it in the media folder
# This was necessary because the src url frequently timed out.
# Here is a link to the workflow: https://github.com/Minituff/save-image

name: Waka Readme Image

on:
  schedule:
    - cron: '0 */24 * * *' # every 24 hours
  workflow_dispatch:

jobs:
  update_wakatime_image:
    runs-on: ubuntu-latest
    name: Save wakatime stats to file
    steps:
      - name: Save my WakaTime stats
        uses: Minituff/save-image@v1.3
        id: waka-image
        with:
          url: 'https://minituff-github-readme-stats.vercel.app/api/wakatime?username=minituff&langs_count=18&layout=compact&custom_title=My%20Code%20Stats'
          imagePath: 'media/wakatime.svg'
      # If you do not commit the changes, then the action does not work
      - name: "Commit changes if necessary"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updating media/wakatime.svg
  
